version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Install curl
          command: apt-get update && apt-get install -y curl
      - run:
          name: "Trigger full-stack test"
          command: "curl -u ${CIRCLE_API_KEY}: -d build_parameters[CIRCLE_JOB]=start_workflows https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/ep-docker/tree/master"
workflows:
  version: 2
  downstream:
    jobs:
      - downstream:
          filters:
            branches:
              only:
                - master